name: "Bug Report"
description: Create a new bug report.
title: "<title>"
labels: []
body:
  - type: textarea
    id: external_urls
    attributes:
      label: "External URLs"
      description: External URLs to, e.g., threads in the Battle.net PTR or bug forums where the bug is mentioned.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of the bug.
      placeholder: Short and explicit description of the bug...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected"
      description: Please enter what should be the expected behavior.
      value: 
      render: bash
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Actual"
      description: Please enter what should is the actual (buggy) behavior.
      value: 
      render: bash
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description how to reproduce the bug.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain the problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: game_versions
    attributes:
      label: "Game Versions"
      description: In which game versions was the bug observed?
      multiple: true
      options:
        - 1.36.1 (1.36.1.20613, 1.36.1.20652)
        - 1.36.0 (1.36.0.20144, 1.36.0.20171, 1.36.0.20200, 1.36.0.20210)
        - 1.35.0 (1.35.0.19721, 1.35.0.19744, 1.35.0.19805, 1.35.0.19836, 1.35.0.19868, 1.35.0.19882, 1.35.0.20030, 1.35.0.20063)
        - 1.34.0 (1.34.0.19572, 1.34.0.19600, 1.34.0.19608)
        - 1.33.0 (1.33.0.18931, 1.33.0.19010, 1.33.0.19019, 1.33.0.19089, 1.33.0.19308)
        - 1.32.10 (1.32.10.18857, 1.32.10.18870)
        - 1.32.9 (1.32.9.16207)
        - 1.32.8 (1.32.8.15762)
        - 1.32.7 (1.32.7.15572)
        - 1.32.6 (1.32.6.15355)
        - 1.32.5 (1.32.5.15129)
        - 1.32.4 (1.32.4.15098)
        - 1.32.3 (1.32.3.14857)
        - 1.32.2 (1.32.2.14722)
        - 1.32.1 (1.32.1.14604)
        - 1.32.0 (1.32.0.14481)
        - 1.31.1 (1.31.1.12164)
        - 1.31.0 (1.31.0.12071)
        - 1.30.4 (1.30.4.11274)
        - 1.30.3 (1.30.3.11235)
        - 1.30.2 (1.30.2.11024)
        - 1.30.1 (1.30.1.10211)
        - 1.30.0 (1.30.0.9900)
        - 1.29.2 (1.29.2.9231)
        - 1.29.1 (1.29.1.9160)
        - 1.29.0 (1.29.0.9055)
        - 1.28f (1.28.3.7680)
        - 1.28e (1.28.4.7608)
        - 1.28d (1.28.3.7205, 1.28.3.7554)
        - 1.28c (1.28.2.7395)
        - 1.28b (1.28.1.7365)
        - 1.28a (1.28.0.7205)
        - 1.27b
        - 1.27a
        - 1.26a?
        - 1.26
        - 1.25b
        - 1.24e
        - 1.24d
        - 1.24c
        - 1.24b
        - 1.24
        - 1.23
        - 1.22
        - 1.21b
        - 1.21
        - 1.20e
        - 1.20d
        - 1.20c
        - 1.20b
        - 1.20
        - 1.19b
        - 1.19
        - 1.18
        - 1.17
        - 1.16
        - 1.15
        - 1.14b
        - 1.14
        - 1.13b
        - 1.13
        - 1.11
        - 1.10
        - 1.07
        - 1.06
        - 1.05
        - 1.04c
        - 1.04
        - 1.03
        - 1.02a
        - 1.02
        - 1.01c
        - 1.01b
        - 1.01
        - 1.00
    validations:
      required: false
